/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.stocktrader.chart.pie;

import java.awt.BorderLayout;
import javafx.application.Platform;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.chart.Chart;
import javafx.scene.chart.PieChart;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;
import org.stocktrader.api.SampleTableModel;
import org.stocktrader.api.StockTraderUtilities;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
    dtd = "-//org.stocktrader.chart.pie//PieChart//EN",
autostore = false)
@TopComponent.Description(
    preferredID = "PieChartTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "org.stocktrader.chart.pie.PieChartTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
    displayName = "#CTL_PieChartAction",
preferredID = "PieChartTopComponent")
@Messages({
    "CTL_PieChartAction=PieChart",
    "CTL_PieChartTopComponent=PieChart Window",
    "HINT_PieChartTopComponent=This is a PieChart window"
})
public final class PieChartTopComponent extends TopComponent {

    private static JFXPanel chartFxPanel;
    private Chart chart;
    private static SampleTableModel tableModel;
    private static ObservableList<PieChart.Data> pcData;

    public PieChartTopComponent() {
        initComponents();
        setName(Bundle.CTL_PieChartTopComponent());
        setToolTipText(Bundle.HINT_PieChartTopComponent());

        setLayout(new BorderLayout());
        init();

    }

    public void init() {
        // Prevent closed windows from killing JavaFX runtime
        // Available in JavaFX 2.2
        //Platform.setImplicitExit(false);
        
        tableModel = StockTraderUtilities.getSampleTableModel();
        chartFxPanel = new JFXPanel();
        add(chartFxPanel, BorderLayout.CENTER);
        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                createScene();
            }
        });
    }

    private void createScene() {
        chart = createPieChart();
        chartFxPanel.setScene(new Scene(chart));
    }

    @SuppressWarnings("unchecked")
    private PieChart createPieChart() {
        final PieChart localChart = new PieChart(getPieChartData());
        localChart.setTitle("Electric Car Sales");
        tableModel.addTableModelListener(new TableModelListener() {

        @Override public void tableChanged(TableModelEvent e) {
            if (e.getType() == TableModelEvent.UPDATE) {
                final int column = e.getColumn();
                double total = 0; 
                int nrows = ((SampleTableModel)e.getSource()).getRowCount();
                for (int row = 0; row < nrows; row++) {
                    total += (Double)((SampleTableModel)e.getSource()).
                        getValueAt(row, column);
                }
                final Double value = total;
                
                Platform.runLater(new Runnable() {
                @Override public void run() {
                    PieChart.Data data = localChart.getData().get(column);
                    data.setPieValue(value);
                    }
                });
            }
        }
        });
        return localChart;
    }
    
    @SuppressWarnings("unchecked")
    public ObservableList<PieChart.Data> getPieChartData() {
        if (pcData == null) {
            pcData = FXCollections.observableArrayList();
            for (int col = 0; col < tableModel.getColumnCount(); col++) {
                double total = 0;
                for (int row = 0; row < tableModel.getRowCount(); row++) {
                    total += (Double)tableModel.getValueAt(row, col);
                }
                pcData.add(
                    new PieChart.Data(tableModel.getColumnName(col), total)); 
            }
        }
        return pcData;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
