/* Generated By:JavaCC: Do not edit this line. SQLParserConstants.java */
package org.netbeans.modules.db.sql.visualeditor.parser;

public interface SQLParserConstants {

  int EOF = 0;
  int AS = 5;
  int ALL = 6;
  int AND = 7;
  int ASC = 8;
  int AVG = 9;
  int BY = 10;
  int COUNT = 11;
  int CROSS = 12;
  int DESC = 13;
  int DISTINCT = 14;
  int FROM = 15;
  int FULL = 16;
  int GROUP = 17;
  int HAVING = 18;
  int INNER = 19;
  int LEFT = 20;
  int JOIN = 21;
  int MAX = 22;
  int MIN = 23;
  int NATURAL = 24;
  int NOT = 25;
  int ON = 26;
  int OR = 27;
  int ORDER = 28;
  int OUTER = 29;
  int RIGHT = 30;
  int SELECT = 31;
  int SUM = 32;
  int WHERE = 33;
  int RELOP = 34;
  int ORDINARY_ID = 35;
  int DELIMITED_ID = 36;
  int MYSQL_DELIMITED_ID = 37;
  int LETTER = 38;
  int DIGIT = 39;
  int STRING_LITERAL = 40;
  int INTEGER_LITERAL = 41;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"AS\"",
    "\"ALL\"",
    "\"AND\"",
    "\"ASC\"",
    "\"AVG\"",
    "\"BY\"",
    "\"COUNT\"",
    "\"CROSS\"",
    "\"DESC\"",
    "\"DISTINCT\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"GROUP\"",
    "\"HAVING\"",
    "\"INNER\"",
    "\"LEFT\"",
    "\"JOIN\"",
    "\"MAX\"",
    "\"MIN\"",
    "\"NATURAL\"",
    "\"NOT\"",
    "\"ON\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"OUTER\"",
    "\"RIGHT\"",
    "\"SELECT\"",
    "\"SUM\"",
    "\"WHERE\"",
    "<RELOP>",
    "<ORDINARY_ID>",
    "<DELIMITED_ID>",
    "<MYSQL_DELIMITED_ID>",
    "<LETTER>",
    "<DIGIT>",
    "<STRING_LITERAL>",
    "<INTEGER_LITERAL>",
    "\",\"",
    "\"*\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"?\"",
  };

}
