/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.cdcatalog.viewer;

import java.awt.BorderLayout;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.BeanTreeView;
import org.openide.explorer.view.IconView;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.nodes.Node;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//org.netbeans.cdcatalog.viewer//CatalogViewer//EN",
autostore = false)
@TopComponent.Description(preferredID = "CatalogViewerTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "org.netbeans.cdcatalog.viewer.CatalogViewerTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_CatalogViewerAction",
preferredID = "CatalogViewerTopComponent")
public final class CatalogViewerTopComponent
        extends TopComponent implements ExplorerManager.Provider {

    public CatalogViewerTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(CatalogViewerTopComponent.class, "CTL_CatalogViewerTopComponent"));
        setToolTipText(NbBundle.getMessage(CatalogViewerTopComponent.class, "HINT_CatalogViewerTopComponent"));

        setLayout(new BorderLayout());

        BeanTreeView btv = new BeanTreeView();
        IconView iv = new IconView();
        add(btv, BorderLayout.CENTER);
//        add(iv, BorderLayout.EAST);

        Children cds = Children.create(new CDChildFactory(), true);
        Node rootNode = new AbstractNode(cds);

        controler.setRootContext(rootNode);
        
associateLookup(ExplorerUtils.
        createLookup(controler, getActionMap()));                

    }
   
    ExplorerManager controler = new ExplorerManager();
    @Override
    public ExplorerManager getExplorerManager() {
        return controler;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
