/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.icon.checkbox.demo;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.OutlineView;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//za.co.kitt.demo.nodesdemo//Status//EN",
autostore = false)
@TopComponent.Description(preferredID = "StatusTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "za.co.kitt.demo.nodesdemo.StatusTopComponent")
@ActionReference(path = "Menu/Window" /*
 * , position = 333
 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_StatusAction",
preferredID = "StatusTopComponent")
public final class StatusTopComponent extends TopComponent implements ExplorerManager.Provider {

    private StatusObject mStatus = new StatusObject(true);
    private final ExplorerManager mgr = new ExplorerManager();

    public StatusTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(StatusTopComponent.class, "CTL_StatusTopComponent"));
        setToolTipText(NbBundle.getMessage(StatusTopComponent.class, "HINT_StatusTopComponent"));

        setLayout(new BorderLayout());

        OutlineView ov = new OutlineView();

        ov.setPropertyColumns(
                "visible", "Status");
        TableColumn columnIndex = ov.getOutline().getColumnModel().getColumn(0);
        ov.getOutline().getColumnModel().removeColumn(columnIndex);

        StatusNode node = new StatusNode(mStatus);
        mgr.setRootContext(node);

        associateLookup(ExplorerUtils.createLookup(mgr, getActionMap()));

        JScrollPane pane = new JScrollPane(ov);

        add(pane, BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return mgr;
    }
}
