/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.oo.workflows;

import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.util.Arrays;
import java.util.Collections;
import javax.swing.JButton;
import net.miginfocom.swing.MigLayout;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.filesystems.FileObject;
import org.openide.filesystems.FileUtil;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//org.oo.workflows//Workflows//EN",
autostore = false)
@TopComponent.Description(preferredID = "WorkflowsTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "output", openAtStartup = true)
@ActionID(category = "Window", id = "org.oo.workflows.WorkflowsTopComponent")
@ActionReference(path = "Menu/Window" /*
 * , position = 333
 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_WorkflowsAction",
preferredID = "WorkflowsTopComponent")
@Messages({
    "CTL_WorkflowsAction=Workflow",
    "CTL_WorkflowsTopComponent=Workflow Navigator",
    "HINT_WorkflowsTopComponent=This is a Workflow window"
})
public final class WorkflowsTopComponent extends TopComponent {

    public WorkflowsTopComponent() {
        initComponents();
        setName(Bundle.CTL_WorkflowsTopComponent());
        setToolTipText(Bundle.HINT_WorkflowsTopComponent());
        setLayout(new MigLayout());
        for (FileObject canvas : FileUtil.getOrder(Arrays.asList(FileUtil.getConfigFile("canvas").getChildren()), true)) {
            JButton button = new JButton();
            button.addActionListener((ActionListener)canvas.getAttribute("actionListener"));
            button.setText(canvas.getName());
            button.setPreferredSize(new Dimension(200,200));
            add(button);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
