/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.google.translator;

import com.google.api.translate.Language;
import javax.swing.JOptionPane;

/**
 *
 * @author geertjan
 */
public class TranslatorPanel extends javax.swing.JPanel {

    /**
     * Creates new form TranslatorPanel
     */
    public TranslatorPanel() {
        initComponents();
    }

    public static Language from() {
        Object sel = fromList.getSelectedValue();
        return getCode(sel);
    }

    public static Language to() {
        Object sel = toList.getSelectedValue();
        return getCode(sel);
    }
    
    public static Language getCode(Object sel) {
        if (sel.equals("French")) {
            return Language.FRENCH;
        } else if (sel.equals("Chinese")) {
            return Language.CHINESE;
        } else if (sel.equals("Chinese (Simplified")) {
            return Language.CHINESE_SIMPLIFIED;
        } else if (sel.equals("Chinese (Traditional")) {
            return Language.CHINESE_TRADITIONAL;
        } else if (sel.equals("English")) {
            return Language.ENGLISH;
        } else if (sel.equals("German")) {
            return Language.GERMAN;
        } else if (sel.equals("Arabic")) {
            return Language.ARABIC;
        } else if (sel.equals("Dutch")) {
            return Language.DUTCH;
        } else if (sel.equals("Japanese")) {
            return Language.JAPANESE;
        } else if (sel.equals("Korean")) {
            return Language.KOREAN;
        } else if (sel.equals("Portuguese")) {
            return Language.PORTUGUESE;
        } else if (sel.equals("Spanish")) {
            return Language.SPANISH;
        } else if (sel.equals("Russian")) {
            return Language.RUSSIAN;
            //All roads lead to Rome:
        } else {
            return Language.ITALIAN;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fromList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        toList = new javax.swing.JList();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(TranslatorPanel.class, "TranslatorPanel.jLabel1.text")); // NOI18N

        fromList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "English", "German", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(fromList);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(TranslatorPanel.class, "TranslatorPanel.jLabel2.text")); // NOI18N

        toList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "English", "German" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(toList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.CENTER)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JList fromList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JList toList;
    // End of variables declaration//GEN-END:variables
}
