/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.gradle.support.options;

import java.io.File;
import org.gradle.tooling.BuildLauncher;
import org.gradle.tooling.GradleConnectionException;
import org.gradle.tooling.GradleConnector;
import org.gradle.tooling.ProjectConnection;
import org.gradle.tooling.ResultHandler;
import org.gradle.tooling.internal.consumer.DefaultGradleConnector;
import org.openide.filesystems.FileChooserBuilder;
import org.openide.util.NbPreferences;

public class GradlePanel extends javax.swing.JPanel {

    private final GradleOptionsPanelController controller;

    GradlePanel(GradleOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        gradleLocField = new javax.swing.JTextField();
        gradleBrowseButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        projectLocField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        verifyGradleButton = new javax.swing.JButton();
        verifyBrowseButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(GradlePanel.class, "GradlePanel.jLabel1.text")); // NOI18N

        gradleLocField.setText(org.openide.util.NbBundle.getMessage(GradlePanel.class, "GradlePanel.gradleLocField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(gradleBrowseButton, org.openide.util.NbBundle.getMessage(GradlePanel.class, "GradlePanel.gradleBrowseButton.text")); // NOI18N
        gradleBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradleBrowseButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        projectLocField.setText(org.openide.util.NbBundle.getMessage(GradlePanel.class, "GradlePanel.projectLocField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(GradlePanel.class, "GradlePanel.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(verifyGradleButton, org.openide.util.NbBundle.getMessage(GradlePanel.class, "GradlePanel.verifyGradleButton.text")); // NOI18N
        verifyGradleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyGradleButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(verifyBrowseButton, org.openide.util.NbBundle.getMessage(GradlePanel.class, "GradlePanel.verifyBrowseButton.text")); // NOI18N
        verifyBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyBrowseButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(GradlePanel.class, "GradlePanel.jLabel3.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(projectLocField, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verifyBrowseButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(verifyGradleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectLocField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verifyBrowseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verifyGradleButton)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(gradleLocField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gradleBrowseButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gradleLocField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradleBrowseButton))
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gradleBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradleBrowseButtonActionPerformed
        FileChooserBuilder fcb = new FileChooserBuilder(System.getProperty("user.home"));
        File f = fcb.showOpenDialog();
        if (f.isDirectory()) {
            File file = f.getAbsoluteFile();
            gradleLocField.setText(file.toString());
        }
    }//GEN-LAST:event_gradleBrowseButtonActionPerformed

    private void verifyBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyBrowseButtonActionPerformed
        FileChooserBuilder fcb = new FileChooserBuilder(System.getProperty("user.home"));
        File f = fcb.showOpenDialog();
        if (f.isDirectory()) {
            File file = f.getAbsoluteFile();
            projectLocField.setText(file.toString());
        }
    }//GEN-LAST:event_verifyBrowseButtonActionPerformed

    private void verifyGradleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyGradleButtonActionPerformed
        if (!gradleLocField.getText().equals("") && !projectLocField.getText().equals("")) {
            File gradleLoc = new File(gradleLocField.getText());
            File projLoc = new File(projectLocField.getText());
            String buildTask = "build";
            ProjectConnection projectConnection = null;
            try {
                GradleConnector gradleConnector = GradleConnector.newConnector();
                gradleConnector.forProjectDirectory(projLoc);
//                gradleConnector.embedded(true);
//                gradleConnector.useClasspathDistribution();
                gradleConnector.useInstallation(gradleLoc);
                projectConnection = gradleConnector.connect();
                try {
                    BuildLauncher launcher = projectConnection.newBuild();
                    launcher.forTasks(new String[]{buildTask});
                    launcher.run(new ResultHandler() {
                        @Override
                        public void onComplete(Object result) {
                            jLabel3.setText("Success!");
                        }
                        @Override
                        public void onFailure(GradleConnectionException failure) {
                            jLabel3.setText("Fail: " + failure.getMessage());
                        }
                    });
                } finally {
                    projectConnection.close();
                }
            } finally {
                if (projectConnection != null) {
                    projectConnection.close();
                }
            }
            
    }//GEN-LAST:event_verifyGradleButtonActionPerformed
        else {
            jLabel3.setText("Fill in the above fields first!");
        }
    }

    void load() {
        // TODO read settings and initialize GUI
        // Example:        
        // someCheckBox.setSelected(Preferences.userNodeForPackage(GradlePanel.class).getBoolean("someFlag", false));
        // or for org.openide.util with API spec. version >= 7.4:
        gradleLocField.setText(NbPreferences.forModule(GradlePanel.class).
                get("gradleLoc", "/home/geertjan/Downloads/gradle/gradle-1.0-milestone-6-20111117000012+0100"));
        // or:
        // someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
    }

    void store() {
        // TODO store modified settings
        // Example:
        // Preferences.userNodeForPackage(GradlePanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        NbPreferences.forModule(GradlePanel.class).put("gradleLoc",
                gradleLocField.getText());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gradleBrowseButton;
    private javax.swing.JTextField gradleLocField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField projectLocField;
    private javax.swing.JButton verifyBrowseButton;
    private javax.swing.JButton verifyGradleButton;
    // End of variables declaration//GEN-END:variables
}
