/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.spring.sample;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//org.spring.sample//Spring//EN",
autostore = false)
@TopComponent.Description(preferredID = "SpringTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "org.spring.sample.SpringTopComponent")
@ActionReference(path = "Menu/Window" /*
 * , position = 333
 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_SpringAction",
preferredID = "SpringTopComponent")
@Messages({
    "CTL_SpringAction=Spring",
    "CTL_SpringTopComponent=Spring Window",
    "HINT_SpringTopComponent=This is a Spring window"
})
public final class SpringTopComponent extends TopComponent {

    public SpringTopComponent() {

        initComponents();

        setName(Bundle.CTL_SpringTopComponent());
        setToolTipText(Bundle.HINT_SpringTopComponent());

        setLayout(new BorderLayout());

        String contextPath = "org/spring/sample/app-context.xml";

        ClassPathXmlApplicationContext ctx = new ClassPathXmlApplicationContext(contextPath);

        add(ctx.getBean("mainPanel", JPanel.class), BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
